[run]
bun = true

[install]
trustedDependencies = ["bun", "@node-rs/argon2", "@node-rs/bcrypt", "esbuild", "sharp"]

[serve.static]
plugins = ["bun-plugin-tailwind"]

[test]
preload = ["./src/test-setup.ts"]
coverage = true
